
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kasperin_dev
    username: dev_user
    password: kasperin
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
#    Use below for generating mysql schema
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: kasperin_database_create.sql

